### ISSUE TITLE
mbeacon broken in combination with Big Sur?

### ISSUE THREAD

**Issue by maagedmazyek** [watr/mbeacon#2]
Hey,

after upgrading to Big Sur I get the error ```Abort trap: 6``` after calling ```mbeacon```. 

Could be this issue: https://stackoverflow.com/questions/30724897/command-failed-due-to-signal-abort-trap-6
or related to missing bluetooth permissions ( ?)

Regards

**Comment by sgrgrsn** [comment]
I have the same issue here on Big Sur 👎

**Comment by watr** [comment]
Thank you for the feedback. I'll fix soon.

I've found related issue and answer.
https://developer.apple.com/forums/thread/111100?answerId=666800022#666800022

**Comment by watr** [comment]
Fixed with #3 👍

**Comment by lettersfromfelix** [comment]
I just noticed I still get this error when trying to start mbeacon - and only got rid of that message when I manually add my terminal to the allowed bluetooth devices in system settings.

**Comment by watr** [comment]
@Flacedoo Thank you for the feedback. I've add a section in README. dcba4a7b7fc307ae36e73dce0a762701af684edb

In my environment (macOS 11.5b5) mbeacon works well if 'automatically add', not requires 'malually add'. If you are still having problems, issue it (like https://github.com/watr/mbeacon/issues/4).
